language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
script:
- python tests.py
install:
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: jacobbridges
  password:
    secure: rRAgxG6QXVV0emTKcrGmRW0LLofac5tSqQtBhU623DIGedFOOEdqinkak+aqWkrnwXxb53rClTcn0jGvEhJuATxtzCYg4hCXvriu53r6f7zoQELbDJZS4BA9S34rkZRb7LcnfIS8use+31SNFlpeqe0QqyLftKOmqHEwnsv7DNVs6Cnzo0r8tcag1cSnvGLutOYRMU8Pb9HtuOH8kga4nzqYLuLvM7Q9qwRdkT6d+hEmAFmzGDttU0P+lGpanTxDVeQPxZ4ksgTXVuvFuGquHRM157ZeLewv3ELUdeijYi6Fwfb8T36Ri1iaPZqpr8KxKVu7aeWKBDYNV7VX0p17D6b05vchrVsfNh5jtSSY9z+bDjvbOpxNubAwBVEaSf4IfpF+EwoVKn776/IsIBZx4eBnFFd3Fk1WfOMI419QGukGUN4Qwn25fqKd3rfmVsHcJCOXSgcwjwfhqVVRAzrc0oO1orgluMpTWvlk7h0t3ry/M/3sAeJ8eVdPGL9zQhwKUItyeEN44sEosFjYG8BZwAhlP2s4OEvsGJ8esD/Qj3B73U2uEH4mVPn/zgyac19KnvV/BiWrtfIlhYMq3qhrA0djpQFEmMPWtfCJ8RWizkqqXzMUSGC2d4zRNmGbWlV9b34frDh0b6WfBJOmsjmvBRX9oKtxBrB6EZ7Dljkmah4=
  on:
    branch: master
